version: "3.8"
services:
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s