# Generated by Django 4.2 on 2023-08-11 19:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('referralcode', models.CharField(max_length=100, unique=True)),
                ('invitecode', models.CharField(blank=True, max_length=100, null=True)),
                ('passcode', models.CharField(blank=True, max_length=200, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('is_invited', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('passcode', models.CharField(max_length=200, verbose_name='Пока не пользователь')),
            ],
            options={
                'verbose_name': 'ПокаНеПользователь',
                'verbose_name_plural': 'ПокаНеПользователи',
            },
        ),
    ]
